export enum MenuKey {
  DASHBOARD = 'DASHBOARD',
  //
  LANDING_PAGE = 'LANDING_PAGE',
  LANDING_PAGE_BANNER = 'LANDING_PAGE_BANNER',
  //
  ORDER = 'ORDER',
  ORDER_ALL = 'ORDER_ALL',
  //
  PRODUCT = 'PRODUCT',
  PRODUCT_LIST = 'PRODUCT_LIST',
  PRODUCT_ADD = 'PRODUCT_ADD',
  PRODUCT_SETTING = 'PRODUCT_SETTING',
  //
  CATEGORY = 'CATEGORY',
  CATEGORY_ROOM = 'CATEGORY_ROOM',
  CATEGORY_STYLE = 'CATEGORY_STYLE',
  CATEGORY_PRODUCT = 'CATEGORY_PRODUCT',
  CATEGORY_HASHTAG = 'CATEGORY_HASHTAG',
  //
  PORTFOLIO = 'PORTFOLIO',
  PORTFOLIO_LIST = 'PORTFOLIO_LIST',
  PORTFOLIO_ADD = 'PORTFOLIO_ADD',
  //
  BLOG = 'BLOG',
  BLOG_LIST = 'BLOG_LIST',
  BLOG_ADD = 'BLOG_ADD',
  BLOG_CATEGORY = 'BLOG_CATEGORY',
  //
  PARTNER = 'PARTNER',
  PARTNER_LIST = 'PARTNER_LIST',
  PARTNER_ADD = 'PARTNER_ADD',
  //
  MARKETING = 'MARKETING',
  MARKETING_SEO = 'MARKETING_SEO',
  MARKETING_SEND_MAIL = 'MARKETING_SEND_MAIL',
  //
  ACCOUNT = 'ACCOUNT',
  //
  MEDIA = 'MEDIA',
}
